spring:
  application:
    name: product-service
server:
  port: 8090
  servlet:
    context-path: /productapp
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/