server:
  port: 8099

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: orderservice
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orderapp/**
            
        - id: productservice
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/productapp/**
            
        - id: customerservice
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customerapp/**
            
        - id: couponservice
          uri: lb://COUPON-SERVICE
          predicates:
            - Path=/couponapp/**         
            
       